title: "Jamie Kent"
description: "Recently returned to Ireland after spending two years in Montreal. Tea and Coffee driven web developer that goes by the name, Jamie. I create clean and beautiful user interfaces on top of solid pragmatic code. I also have experience in the back end, creating accessible API’s and effective secure servers. I love learning new technologies and working on interesting projects. My goal is to build products that people love using!
"
about: "Recently returned to Ireland after spending two years in Montreal. Tea and Coffee driven web developer that goes by the name, Jamie. I create clean and beautiful user interfaces on top of solid pragmatic code. I also have experience in the back end, creating accessible API’s and effective secure servers. I love learning new technologies and working on interesting projects. My goal is to build products that people love using!
"
location: "Wexford, Ireland"
email: jameskent91@gmail.com
baseurl: ""

url: "http://jameskent.github.io/" # replace by your site's url
twitter_username: James0888
github_username:  JamesKent
author: "Jamie Kent"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
